_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 53
                - 55
            "2":
                - 1
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.5
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
chain:
    value:
        burn_in: 500
        dims:
            - 4
            - 4
        length: 300
        rank: 5
general:
    value:
        data_path: data/
        save_path: results/
        seed: 1000
        trials: 5
        use_wandb: true
method:
    value:
        K: null
        dc:
            alpha: 0.1
            beta: 1
            gamma: 1
            inn_tol: 1e-07
            num_inn_itrs: 10
            pmin: 1e-06
            verbose: true
        ent:
            ACCELERATION: true
            ALPHA_TYPE: adam
            B: null
            INCREASE_B: false
            alpha_factor: 1
            alpha_weight: 1
            beta: 0.5
            eps: 1e-09
            gamma_factor: 0.3
            gamma_weight: 0.3
            qmax: 1
            qmin: 1e-06
            slide_window: 1000
            tol: 1e-08
        fib:
            ACCELERATION: true
            ALPHA_TYPE: adam
            B: null
            INCREASE_B: false
            alpha_factor: 1
            alpha_weight: 1
            beta: 0.5
            eps: 1e-09
            gamma_factor: 0.3
            gamma_weight: 0.3
            qmax: 1
            qmin: 1e-06
            slide_window: 1000
            tol: 1e-08
        method_name: dc
        nn:
            beta: 1
            gamma: 1
            pmin: 1e-06
            verbose: true
        sm:
            qmin: 1e-06
        traj:
            ACCELERATION: true
            ALPHA_TYPE: adam
            B: null
            INCREASE_B: false
            alpha_factor: 1
            alpha_weight: 1
            beta: 0.5
            eps: 1e-09
            gamma_factor: 0.3
            gamma_weight: 0.3
            qmax: 1
            qmin: 1e-06
            slide_window: 1000
            tol: 1e-08
training:
    value:
        eval_every: 50
        num_iters: 1000
        save: true
        slide_window: 1000
        tol: 1e-07
