general:
  seed: 1000
  save_path: "results/"

dataset:
  trips_path: "data/yellow_tripdata_2024-01.parquet"
  zones_path: "data/taxi_zones.csv"
  data_dir: "data"
  trials: 5
  n_samples: 100
  n_samples_all: [100, 500, 1000]

method:
  method_name: "dc"