general:
  seed: 1000
  save_path: "results/"

dataset:
  dims: [4, 4]
  data_dir: "data"
  rank: 5
  burn_in: 500
  length: 300
  trials: 5
  generation_type: "tensor"
  generation_method: "lowrank"

method:
  method_name: "dc"