description: Sweep test using dc estimation

# program and project only used when running sweep from CLI
program: sweep.py
project: markov-chain-estimation

method: grid
metric:
  name: qkld
  goal: minimize

parameters:
  method:
    parameters:
      method_name:
        value: "dc"
      dc:
        parameters:
          num_itrs:
            value: 5000
          K:
            values: [ 3, 6 ]
          alpha:
            value: 0.1
          gamma:
            value: 0.1
          num_inn_itrs:
            value: 10
