description: Sweep test using fib estimation

# program and project only used when running sweep from CLI
program: sweep.py
project: markov-chain-estimation

method: grid
metric:
  name: qkld
  goal: minimize

parameters:
  method:
    parameters:
      method_name:
        value: "ent"
      ent:
        parameters:
          num_itrs:
            value: 10000
          B:
            value: 20
          B_max:
            value: 100
          increase_B:
            value: False
          K:
            values: [ 3, 5, 7 ]
          alpha_factor:
            values: [ .01, .1 ]
          alpha_weight:
            values: [ .01, .1 ]
          gamma_factor:
            value: 0.1
          gamma_weight:
            value: 0.1
          beta:
            value: .5

