description: Sweep test using fib estimation

# program and project only used when running sweep from CLI
program: sweep.py
project: markov-chain-estimation

method: grid
metric:
  name: qkld
  goal: minimize

parameters:
  method:
    parameters:
      method_name:
        value: "fib"
      fib:
        parameters:
          num_itrs:
            value: 10000
          forget_window:
            value: 5000
          B:
            value: 20
          B_max:
            value: 100
          increase_B:
            value: True
          K:
            values: [ 10, 20 ]
          alpha_factor:
            values: [ 10., 20. ]
          alpha_weight:
            values: [ 5., 10. ]
          gamma_factor:
            value: 0.5
          gamma_weight:
            value: 0.2
          beta:
            value: .3
          tol:
            value: 1e-9
